name: resident_app

melos: 
  sdkPath: .fvm/flutter_sdk

packages:
  - packages/**
  - lib/**

scripts:
  analyze:
    exec: dart analyze .
  build_files:
    exec: dart run build_runner build --delete-conflicting-outputs
  get:
    exec: dart pub get
    concurrency: 10
  setup:
     melos bootstrap && dart run build_runner build --delete-conflicting-outputs && dart analyze .
