name: resident_app

packages:
  - packages/**
  - lib/**

scripts:
  analyze:
    exec: dart analyze .
  build_files:
    exec: dart run build_runner build --delete-conflicting-outputs
  get:
    exec: dart pub get
  setup:
     melos bootstrap && dart run build_runner build --delete-conflicting-outputs && dart analyze .
