name: resident_app
description: HomeLINK Resident App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: 9.0.0
  carousel_slider: 5.0.0
  equatable: 2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: 9.0.0
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  property_api_client:
    path: packages/property_api_client
  property_repository:
    path: packages/property_repository
  shared_preferences: 2.4.0

dev_dependencies:
  bloc_test: 10.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  melos: 6.3.2
  mocktail: 1.0.4
  very_good_analysis: 6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/devices/
