name: property_api_client
description: Property package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  build_runner: ^2.4.11
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
